[package]
name = "seu_wlan_login"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["blocking"] }
thiserror = "2.0.18"
regex = "1.13.0"
serde_json = "1.0.150"
serde = { version = "1.0.228", features = ["derive"] }
base64 = "0.22.1"
rpassword = "7.5.4"